name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: yarn install
      - run: yarn build
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: yarn install
      - run: yarn build
      - name: Set up Cloud DOC
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: config project
        run: gcloud config set project r2u-sdk
      - name: Copy build to bucket
        run: gsutil -m cp -r ./build/* gs://doc-r2u-bucket
      - name: Set as index page
        run: gsutil web set -m index.html gs://doc-r2u-bucket
      - name: Invalidate cache
        run: gcloud compute url-maps invalidate-cdn-cache doc-r2u-lb --async --path=/* 