name: Format

on:
  push:
    branches:
      - master

jobs:
  prettier:
    name: Run Prettier
    runs-on: ubuntu-latest
    if: github.actor != 'bot@r2u.io'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: yarn install
      - name: Run Prettier
        run: yarn prettier
      - name: Commit changes
        run: |
          git config user.email 'bot@r2u.io'
          git config user.name 'R2U Bot'
          git add .
          git diff-index --quiet HEAD || (git commit -m 'Run Prettier - R2U Bot' && git push)
