name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  prettier:
    name: Run Prettier
    runs-on: ubuntu-latest
    if: github.actor != 'bot@r2u.io'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Run Prettier
        run: npx prettier --write .
      - name: Commit changes
        run: |
          git config user.email 'bot@r2u.io'
          git config user.name 'R2U Bot'
          git add .
          git diff-index --quiet HEAD || (git commit -m 'Run Prettier - R2U Bot' && git push)
          yarn install
  build:
    name: Build 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v1
      - name: Setup node
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: yarn install
      - run: yarn build
  deploy:
    name: Deploy
    needs: [build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
      - uses: actions/checkout@v1
      - name: Setup node
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - uses: webfactory/ssh-agent@v0.5.0
      - name: Release to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: git
      - run: yarn install
      - run: yarn build
      - run: yarn deploy